# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jrighi <jrighi@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/17 16:55:23 by jrighi            #+#    #+#              #
#    Updated: 2025/01/22 23:58:20 by jrighi           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = so_long

CC = cc
CFlAGS = -Wall -Wextra -Werror
MLX	= minilibx-linux/Makefile.gen
INC = -I ./inc -I ./minilibx-linux
LIB = -L ./minilibx-linux -lmlx -lXext -lx11 -lm -lbsd
